title: Home of Diskbuster 
email: mail@diskbuster.de
description: "stuff and more selected by diskbuster"
baseurl: ''
url: 'https://diskbuster.de/'
twitter:
  username: "diskbuster"
github:
  username: "diskbuster"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
footer:
  links:
   

author:
  name: "Joachim Kasper"
  avatar: "/assets/images/db_logo.jpg"
  bio: "<p>I am that guy who take crap off someone when it comes to Internet Developement and Media Design.</p>
  <p>Feel free to read my writings and get in touch if you like."
  location: "Sunnyhill, Osnabrück, Germany"
  links:
    - label: "mail@diskbuster.de"
      icon: "fas fa-fw fa-paper-plane"
      url: "mailto:mail@diskbuster.de"
    - label: "diskbuster.de"
      icon: "fas fa-fw fa-home"
      url: "https://diskbuster.de"
    - label: "find me on GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/diskbuster"
